create database ListtaVip;

CREATE TABLE users (
id SERIAL PRIMARY KEY,
name VARCHAR(255) DEFAULT NULL,
birthdate DATE DEFAULT NULL,
phone VARCHAR(20) DEFAULT NULL,
email VARCHAR(255) DEFAULT NULL,
category VARCHAR(50) DEFAULT NULL,
password VARCHAR(255) DEFAULT NULL,
confirm_password VARCHAR(255) DEFAULT NULL,
address TEXT DEFAULT NULL,
credits INTEGER NOT NULL DEFAULT 0,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
plan VARCHAR(255) DEFAULT NULL,
image_url VARCHAR(255) DEFAULT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  deposit_pending DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  deposit_confirmed DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  bonus DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  last_deposit TIMESTAMP,
  last_withdrawal TIMESTAMP,
  last_bonus TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);
