create database ListtaVip;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) DEFAULT NULL,
  birthdate DATE DEFAULT NULL,
  phone VARCHAR(20) DEFAULT '',
  email VARCHAR(255) UNIQUE NOT NULL,
  category VARCHAR(50) DEFAULT '',
  password VARCHAR(255) NOT NULL,
  confirm_password VARCHAR(255) NOT NULL,
  address TEXT DEFAULT '',
  credits INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  plan VARCHAR(255) DEFAULT '',
  image_url VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS accounts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  deposit_pending DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  deposit_confirmed DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  bonus DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  last_deposit TIMESTAMP,
  last_withdrawal TIMESTAMP,
  last_bonus TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);
